/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
