/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl.ui.tests;

import com.google.inject.Injector;
import kit.mdsd.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("kit.mdsd.xtext.dsl.Dsl");
	}

}
