/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DslScopeProvider extends AbstractDslScopeProvider {

}
