/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
