/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://metaModel"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://metaModel/viewType/assembly"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://metaModel/viewType/repository"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://metaModel/viewType/environment"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://metaModel/viewType/allocation"));
		return result;
	}
}
