/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DslUiModule extends AbstractDslUiModule {

	public DslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
