/*
 * generated by Xtext 2.30.0
 */
package kit.mdsd.xtext.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kit.mdsd.xtext.dsl.DslRuntimeModule;
import kit.mdsd.xtext.dsl.DslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslIdeSetup extends DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslRuntimeModule(), new DslIdeModule()));
	}
	
}
