<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metaModel" nsURI="http://metaModel" nsPrefix="metaModel">
  <eSubpackages name="viewType" nsURI="http://metaModel/viewType" nsPrefix="metaModel.viewType">
    <eSubpackages name="repository" nsURI="http://metaModel/viewType/repository" nsPrefix="metaModel.viewType.repository">
      <eClassifiers xsi:type="ecore:EClass" name="Component">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
            eType="#//viewType/repository/Interface"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
            eType="#//viewType/repository/Interface"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//viewType/repository/BehaviourDescription"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Interface">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="signatures" upperBound="-1"
            eType="#//viewType/repository/Signature"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectorRequired"
            lowerBound="1" eType="#//viewType/assembly/DelegationConnectorRequired"
            eOpposite="#//viewType/assembly/DelegationConnectorRequired/linkedInterface"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnectorProvided"
            lowerBound="1" eType="#//viewType/assembly/DelegationConnectorProvided"
            eOpposite="#//viewType/assembly/DelegationConnectorProvided/linkedInterface"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParameterType" abstract="true" eSuperTypes="#//viewType/repository/Type"/>
      <eClassifiers xsi:type="ecore:EClass" name="Signature">
        <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" lowerBound="1"
            eType="#//viewType/repository/Type"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
            eType="#//viewType/repository/Parameter"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Parameter">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//viewType/repository/ParameterType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Repository">
        <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
            eType="#//viewType/repository/Component" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
            eType="#//viewType/repository/Interface" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BehaviourDescription">
        <eStructuralFeatures xsi:type="ecore:EReference" name="internalActions" upperBound="-1"
            eType="#//viewType/repository/InternalAction" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="externalCalls" upperBound="-1"
            eType="#//viewType/repository/ExternalCall" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="loops" upperBound="-1"
            eType="#//viewType/repository/Loop" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
            eType="#//viewType/repository/Branch" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SimpleType" abstract="true" eSuperTypes="#//viewType/repository/ParameterType"/>
      <eClassifiers xsi:type="ecore:EClass" name="ComplexType" eSuperTypes="#//viewType/repository/ParameterType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="types" lowerBound="1"
            upperBound="-1" eType="#//viewType/repository/ParameterType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="InternalAction"/>
      <eClassifiers xsi:type="ecore:EClass" name="ExternalCall"/>
      <eClassifiers xsi:type="ecore:EClass" name="Loop"/>
      <eClassifiers xsi:type="ecore:EClass" name="Branch"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Map" instanceClassName="java.util.Map"/>
      <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Int" instanceClassName="java.lang.Integer"/>
      <eClassifiers xsi:type="ecore:EDataType" name="List" instanceClassName="java.util.List"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Date" instanceClassName="java.util.Date"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Long" instanceClassName="java.lang.Long"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Float" instanceClassName="java.lang.Float"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Char" instanceClassName="java.lang.Character"/>
      <eClassifiers xsi:type="ecore:EDataType" name="Void" instanceClassName="java.lang.Void"/>
      <eClassifiers xsi:type="ecore:EClass" name="MapType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Map" lowerBound="1"
            eType="#//viewType/repository/Map"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="String" lowerBound="1"
            eType="#//viewType/repository/String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Boolean" lowerBound="1"
            eType="#//viewType/repository/Boolean"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="IntType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Int" lowerBound="1"
            eType="#//viewType/repository/Int"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ListType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="List" lowerBound="1"
            eType="#//viewType/repository/List"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DateType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" lowerBound="1"
            eType="#//viewType/repository/Date"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="LongType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Long" lowerBound="1"
            eType="#//viewType/repository/Long"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="FloatType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Float" lowerBound="1"
            eType="#//viewType/repository/Float"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CharType" eSuperTypes="#//viewType/repository/SimpleType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="Char" lowerBound="1"
            eType="#//viewType/repository/Char"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//viewType/repository/Type">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" lowerBound="1"
            eType="#//viewType/repository/Void"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="assembly" nsURI="http://metaModel/viewType/assembly" nsPrefix="metaModel.viewType.assembly">
      <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="instanceOf" lowerBound="1"
            eType="#//viewType/repository/Component"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
            eType="#//viewType/assembly/ProvidedRole"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
            eType="#//viewType/assembly/RequiredRole"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//viewType/repository/Component">
        <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedInstances"
            lowerBound="1" upperBound="-1" eType="#//viewType/assembly/AssemblyContext"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="System">
        <eStructuralFeatures xsi:type="ecore:EReference" name="encapsulatedInstances"
            lowerBound="1" upperBound="-1" eType="#//viewType/assembly/AssemblyContext"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="provides" lowerBound="1"
            upperBound="-1" eType="#//viewType/repository/Interface"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//viewType/assembly/Role">
        <eStructuralFeatures xsi:type="ecore:EReference" name="delegationConnector"
            lowerBound="1" eType="#//viewType/assembly/DelegationConnectorRequired"
            eOpposite="#//viewType/assembly/DelegationConnectorRequired/linkedRole"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyconnector"
            lowerBound="1" eType="#//viewType/assembly/AssemblyConnector" eOpposite="#//viewType/assembly/AssemblyConnector/requiredrole"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DelegationConnectorRequired" eSuperTypes="#//viewType/assembly/DelegationConnector">
        <eStructuralFeatures xsi:type="ecore:EReference" name="linkedRole" lowerBound="1"
            eType="#//viewType/assembly/RequiredRole" eOpposite="#//viewType/assembly/RequiredRole/delegationConnector"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="linkedInterface" lowerBound="1"
            eType="#//viewType/repository/Interface" eOpposite="#//viewType/repository/Interface/delegationConnectorRequired"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
        <eStructuralFeatures xsi:type="ecore:EReference" name="providedRole" lowerBound="1"
            eType="#//viewType/assembly/ProvidedRole" eOpposite="#//viewType/assembly/ProvidedRole/assemblyConnector"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" lowerBound="1"
            eType="#//viewType/assembly/RequiredRole" eOpposite="#//viewType/assembly/RequiredRole/assemblyconnector"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Role" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//viewType/assembly/Role">
        <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyConnector"
            eType="#//viewType/assembly/AssemblyConnector" eOpposite="#//viewType/assembly/AssemblyConnector/providedRole"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector" abstract="true"/>
      <eClassifiers xsi:type="ecore:EClass" name="DelegationConnectorProvided" eSuperTypes="#//viewType/assembly/DelegationConnector">
        <eStructuralFeatures xsi:type="ecore:EReference" name="linkedRole" lowerBound="1"
            eType="#//viewType/assembly/ProvidedRole"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="linkedInterface" lowerBound="1"
            eType="#//viewType/repository/Interface" eOpposite="#//viewType/repository/Interface/delegationConnectorProvided"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="environment" nsURI="http://metaModel/viewType/environment"
        nsPrefix="metaModel.viewType.environment">
      <eClassifiers xsi:type="ecore:EClass" name="Container">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Link">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="containers" lowerBound="2"
            upperBound="-1" eType="#//viewType/environment/Container"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Enivronment">
        <eStructuralFeatures xsi:type="ecore:EReference" name="container" upperBound="-1"
            eType="#//viewType/environment/Container" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1"
            eType="#//viewType/environment/Link" containment="true"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="allocation" nsURI="http://metaModel/viewType/allocation" nsPrefix="metaModel.viewType.allocation">
      <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
        <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
            eType="#//viewType/environment/Container"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyContext" lowerBound="1"
            eType="#//viewType/assembly/AssemblyContext"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
